version: '3'
services:
  node-api:
    build:
      context: .
      dockerfile: conf/node-api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/back:/usr/src/app/api
      - /usr/src/app/api/node_modules
  angular:
    build:
      context: .
      dockerfile: conf/angular/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./apps/front:/usr/src/app/front
      - /usr/src/app/front/node_modules